// <auto-generated />
namespace Online_Grocery_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ninth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ninth));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301833339_ninth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
